#!/bin/bash
#do not edit this file
rm nosetests.json
rm $1/test_summary.txt

echo "Running the linter (checking your code style)..."
cd ..
PYTHONPATH=./exercise:$PYTHONPATH pylint --disable=R,C exercise/ --ignore=venv
exit_status=$?
echo $exit_status
if [ $exit_status != 0 ]; then
  echo "Your code has failed the style checks, please check the logs. No score recorded."
  exit 1
fi
cd exercise

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac
if [[ $machine == "Linux" ]];
then
	timeout 60 python -m nose --with-json-extended
else
	python3 -m nose --with-json-extended
fi
if [[ $? == 124 ]];
then
	echo "Tests took too long -- score was not recorded"
	exit 1
fi

total=`jq '.modules | map_values([.nr_failed, .nr_success, .nr_error]) | add | add' nosetests.json`
success=`jq '.modules | map_values([.nr_success]) | add | add' nosetests.json`
echo "Recording result of passed tests: $success out of $total..."
echo "total/$total/passed/$success" > $1/test_summary.txt
if [[ $total == $success ]];
then
	echo "all tests passed - well done"
	exit 0
else
	echo "some tests failed. please check the logs to see why."
	exit 1
fi